### ISSUE TITLE
Error during build:  installation of package 'gert' had non-zero exit status

### ISSUE THREAD

**Issue by lucasfr** [RealityBending/TemplateResults#1]
Hello

I made a fork of this repository intending to add reticulate and make a version that can also knit Python code.
However it returned the following error:

> Quitting from lines 41-45 (index.Rmd) 
> Error: Error: Failed to install 'easystats' from GitHub:
> (converted from warning) installation of package 'gert' had non-zero exit status
> Execution halted
> Error: Process completed with exit code 1.

The only solution to it was to comment out the two following lines on utils/config.R file:

if (!"report" %in% installed) remotes::install_github("easystats/report")
if (!"easystats" %in% installed) remotes::install_github("easystats/easystats")

Given that the build seem to have been completed in this repository, I assume something changed in the two easystats repositories. 

Would you have any clues on why that is happening? Or have any idea of how to fix it?

**Comment by DominiqueMakowski** [comment]
Indeed, the same error started impacting my own projects yesterday 😕 

I don't know yet why / how to fix it, but it could *perhaps* be addressed by removing the installation of easystats (though [easystats itself](https://github.com/easystats/easystats/blob/master/DESCRIPTION) is a package without any other dependencies, so I'm not sure why would it be the one causing it). 

Seeing the scope of "gert", it might be some low-level issue related to some obscure stuff... I'll investigate and update this thread if I find anything!

**Comment by DominiqueMakowski** [comment]
@lucasfr so I basically removed `easystats` from the packages that are installed, and it seems to work now ☺️ 

Let me know how it goes!

**Comment by lucasfr** [comment]
@DominiqueMakowski  Thank you. yes, it worked for me when I commented them out. 
I also managed to get reticulate working, if you are interested. Had to work on it a bit...
You mayclose the issue, if that's OK with you.

**Comment by DominiqueMakowski** [comment]
thanks again for reporting this issue!

> I also managed to get reticulate working, if you are interested. Had to work on it a bit...

By all means 🙌  can you share the code of the action to get it running? Maybe in a new issue so that future googlers can easily fit it
