### ISSUE TITLE
Action for installing reticulate and adding Python Support

### ISSUE THREAD

**Issue by lucasfr** [RealityBending/TemplateResults#2]
I have adapted the original action to install reticulate. The trick is it must be the Github version for some reason. A new version is available in https://github.com/lucasfr/TemplateResults/blob/main/.github/workflows/build.yml.

It consists of adding the following lines to the dependencies install section:

> Rscript -e "remotes::install_github('rstudio/reticulate')"
> Rscript -e "reticulate::install_miniconda()"

Then install the dependencies by adding the following line to utils/config.R (it can probably be added to the action file too!)

> py_install(packages = c('numpy', 'scipy', 'seaborn', 'matplotlib'))

Might be a good idea to include these on this repository - perhaps as commented lines in case someone is interested?

**Comment by DominiqueMakowski** [comment]
I added it in the template, thanks a lot ☺️
