### ISSUE TITLE
Permission to use the template for a github page

### ISSUE THREAD

**Issue by JauntyJJS** [RealityBending/TemplateResults#3]
Hi,

I have used and adapt the template to create a html document to explain how the paper [BioPAN](https://f1000research.com/articles/10-4) generate those numbers in their output graphs using a running example

![image](https://user-images.githubusercontent.com/9066508/118364355-ba62f200-b5ca-11eb-8281-46efad2915e6.png)

Here is a link to the work which I am planning to turn it to a GitHub page...
https://github.com/JauntyJJS/BioPAN_Tutorial

May I ask how to I give attribute/credit to this template ?

Kindly advise.

**Comment by DominiqueMakowski** [comment]
Hi @JauntyJJS , nice work, and thanks for asking. There is no standard way of crediting this, aside from citing the GitHub repo (tbh I didn't expect people to do that so thanks for considering it!). If you wish, you can drop somewhere a small link to this page, for example "[Inspired by Makowski's Results Template](https://github.com/RealityBending/TemplateResults)" or something like that ☺️

Glad that it helped, cheers!

**Comment by JauntyJJS** [comment]
Thank you for the feedback. I will close the issue.
The html document can be viewed here.
https://jauntyjjs.github.io/BioPAN_Tutorial/
